# Generated by Django 5.1.2 on 2025-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(help_text='GitHub/Live demo URL')),
                ('year', models.PositiveIntegerField()),
                ('batch', models.CharField(help_text='e.g. ’2021–25’', max_length=20)),
                ('branch', models.CharField(help_text='e.g. Computer Science', max_length=100)),
                ('project_type', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
