# Generated by Django 5.1.2 on 2025-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_batch_project_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
